<a href="https://colab.research.google.com/github/jampi222/inteligencia-artificial/blob/main/explorinNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np

# Check the NumPy version
print(np.__version__)

1.23.5


In [ ]:
# Create a 1D array of numbers from 0 to 9
array_1d = np.arange(10)

print(array_1d)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)


Random vector with the maximum value replaced by 0:
[0.67087963 0.49034208 0.85653044 0.90943416 0.1292748  0.
 0.4248233  0.09431999 0.34777831 0.42009835]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# To print the number 8
number_to_find = 8

indices = np.where(arr == number_to_find)

print("Indices of the number 8:")
print(indices)

found_value = arr[indices]
print("The number 8 is at position:", indices[0], indices[1])
print("Value at that position:", found_value)

Indices of the number 8:
(array([1]), array([2]))
The number 8 is at position: [1] [2]
Value at that position: [8]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use slicing to extract the numbers [3, 4, 5]
subset = arr[2:5]

print("The numbers [3, 4, 5] from the array:")
print(subset)

The numbers [3, 4, 5] from the array:
[3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use slicing to extract the last 4 numbers
a = arr[-4:]

print("The last 4 numbers from the array:")
print(a)

The last 4 numbers from the array:
[4 5 6 7]


In [ ]:
t = np.ones((2, 2), dtype=bool)

print(t)

[[ True  True]
 [ True  True]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to extract odd numbers
odd_numbers = arr[arr % 2 == 1]

print("Odd numbers from the array:")
print(odd_numbers)

Odd numbers from the array:
[1 3 5 7 9]


In [ ]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
random_array = np.random.randint(0, 101, size=(10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
[[13 57 78 58 12 93 82 29 51 34]
 [82 32 28 21 84 83 58 80 13 39]
 [64 18 52 35 74 92 53 77 34 30]
 [71 60 35 71 99 19 41 36 59 17]
 [36 31 25 33 69 66  7  1 83 28]
 [28 23 81 36 60  7 64 19 86 29]
 [62 67 12 18 32  2 90 53 68 38]
 [99 67  6 93 25 36 90 87 14 84]
 [42 21 94 86 27 18 48 77 80 93]
 [33 31 27 68 41  6 47 20 41  0]]
Minimum Value: 0
Maximum Value: 99


In [ ]:
randon = np.random.rand(3, 3, 3)

print(randon)

[[[0.20810817 0.72523111 0.19621172]
  [0.42467001 0.2706585  0.5303172 ]
  [0.05807656 0.97474591 0.57734452]]

 [[0.56609884 0.42129758 0.9445945 ]
  [0.64033202 0.30971608 0.43400677]
  [0.92092345 0.17812725 0.03376925]]

 [[0.78257558 0.21707406 0.67710168]
  [0.97915025 0.0470139  0.89001353]
  [0.86137091 0.25416537 0.4516412 ]]]


In [ ]:
import numpy as np

# Create or define your NumPy array (arr)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to replace odd numbers with -1
arr[arr % 2 == 1] = -1

print("Modified array with odd numbers replaced by -1:")
print(arr)


Modified array with odd numbers replaced by -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
float_array = np.array([1.3, 2.5, 3.7, 4.2])

print(float_array)

[1.3 2.5 3.7 4.2]


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the 1D array into a 2D array with 2 rows
arr_2d = arr_1d.reshape(2, -1)

print("1D Array:")
print(arr_1d)

print("2D Array with 2 rows:")
print(arr_2d)

1D Array:
[1 2 3 4 5 6 7 8]
2D Array with 2 rows:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Find the common values between Z1 and Z2
common_values = np.intersect1d(Z1, Z2)

print("Array Z1:", Z1)
print("Array Z2:", Z2)
print("Common values:", common_values)




Array Z1: [2 9 4 2 6 1 0 6 1 8]
Array Z2: [5 9 4 7 2 4 8 8 8 6]
Common values: [2 4 6 8 9]


In [ ]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [1 1 0 1 1]
Array B: [0 0 0 1 0]
Are A and B equal? False


In [ ]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])

# Stack arrays a and b vertically
stacked_array = np.vstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (vertically):")
print(stacked_array)

Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (vertically):
[[0 2 5]
 [0 2 5]]


In [ ]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])

# Stack arrays a and b horizontally
stacked_array = np.hstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (horizontally):")
print(stacked_array)

Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (horizontally):
[0 2 5 0 2 5]


In [ ]:
tmp = np.arange(15)

# Create a boolean mask to identify elements between 5 and 10
mask = (tmp >= 5) & (tmp <= 10)

# Use the boolean mask to extract elements between 5 and 10
result = tmp[mask]

print("Array tmp:")
print(tmp)

print("Items between 5 and 10:")
print(result)

Array tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Items between 5 and 10:
[ 5  6  7  8  9 10]


In [ ]:
def pair_max(a, b):
    """Get the element-wise maximum of two arrays a and b."""
    return np.maximum(a, b)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


In [ ]:
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("Array after swapping columns 1 and 2:")
print(arr)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after swapping columns 1 and 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
random_array = np.random.uniform(5, 10, size=(5, 3))

print(random_array)


[[5.07695792 8.13353125 7.63725627]
 [8.93930692 8.62480132 6.57785557]
 [8.45080903 5.3431797  8.95482708]
 [9.27924125 6.83049599 9.04400256]
 [7.59892454 5.48367735 7.85655403]]
