<a href="https://colab.research.google.com/github/jampi222/inteligencia-artificial/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

aux=np.array({1,2,4,5})
print(aux)
print(aux.shape)


aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))



tmp=np.zeros((4,4))
print(tmp)

tmp=np.full((4,4),5)
print(tmp)


tmp=np.eye(4,4)
print(tmp)


print('--------------')
tmp=np.ones((4,4))
print(tmp)

{1, 2, 4, 5}
()
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)



[[6.01037708 1.61261523 0.79273471]
 [1.62805293 8.63841385 1.98933707]
 [5.12136548 8.18126408 7.4007034 ]]


In [ ]:
print(tmp[:2,:2])

[[6.01037708 1.61261523]
 [1.62805293 8.63841385]]


In [ ]:
print(tmp[:2,1:3])

[[1.61261523 0.79273471]
 [8.63841385 1.98933707]]


In [ ]:
print(tmp[:1,1])
print(tmp[2,2])
print(tmp[2,1:3])

[1.61261523]
7.4007033951942445
[8.18126408 7.4007034 ]


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)


[[5.84830279 9.62548768 8.96932321]
 [1.16339102 7.37356925 7.88714608]
 [4.18479057 7.22096919 3.67385514]]


In [ ]:
mask=(tmp>=2)&(tmp<=4)


[3.67385514]


In [ ]:
tmp= np.random.randint(1, 101, (4, 4))
print(tmp)
mask =np.mod(tmp, 2) == 0
matriz_pares = tmp[mask]
print(tmp[mask])

[[99 60 90 53]
 [97 95 79 26]
 [56 47 32 76]
 [78 29 19 36]]
[60 90 26 56 32 76 78 36]
