<a href="https://colab.research.google.com/github/jampi222/inteligencia-artificial/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(1, 11, size=(3,4))
b=np.random.randint(1, 11, size=(3,4))
print(a)
print(b)

[[ 5  4 10  1]
 [ 6  5 10  4]
 [ 6  2  7  1]]
[[ 2  7  5  2]
 [10  6  8  9]
 [10  1 10  9]]


In [ ]:
print(a.shape)
print(b.shape)

(3, 4)
(3, 4)


In [ ]:
print('Adding numbers')
#plus
print(a+b)
print('Subtracting numbers')
#minus
print(a-b)
print('Multiplication numbers')
#times
print(a*b)

Adding numbers
[[ 7 11 15  3]
 [16 11 18 13]
 [16  3 17 10]]
Subtracting numbers
[[ 3 -3  5 -1]
 [-4 -1  2 -5]
 [-4  1 -3 -8]]
Multiplication numbers
[[10 28 50  2]
 [60 30 80 36]
 [60  2 70  9]]


In [ ]:
print('Add')
print(np.add(a,b))
print('Substract')
print(np.multiply(a,b))
print('Multiply')
print(np.subtract(a,b))
print('Divide')
print(np.divide(a,b))

Add
[[ 7 11 15  3]
 [16 11 18 13]
 [16  3 17 10]]
Substract
[[10 28 50  2]
 [60 30 80 36]
 [60  2 70  9]]
Multiply
[[ 3 -3  5 -1]
 [-4 -1  2 -5]
 [-4  1 -3 -8]]
Divide
[[2.5        0.57142857 2.         0.5       ]
 [0.6        0.83333333 1.25       0.44444444]
 [0.6        2.         0.7        0.11111111]]


In [ ]:
m1 = np.random.randint(1, 11, size=(3,4))
m2 = np.random.randint(1, 11, size=(4,8))
print(m1)
print(m1.shape)
print(m2)
print(m2.shape)

[[ 3  9  5  4]
 [ 3  9  4  5]
 [10  6  2  5]]
(3, 4)
[[ 6  9  4  3  5  4  1  7]
 [ 2  8  2  3  4  8 10 10]
 [ 2  8  1  7  8  3 10  8]
 [ 3  9  4  1  8  9  2  5]]
(4, 8)


In [ ]:
print(m1.dot(m2))
print(np.dot(m1,m2).shape)

[[ 58 175  51  75 123 135 151 171]
 [ 59 176  54  69 123 141 143 168]
 [ 91 199  74  67 130 139 100 171]]
(3, 8)


In [ ]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[9 6]
 [1 1]]
[[9 1]
 [6 1]]


In [ ]:
#broadcast
x = np.random.randint(1, 11, size=(4,3))
y = np.array([1,0,2])

print(x.shape)
print(y.shape)

(4, 3)
(3,)


In [ ]:
z=np.empty_like(x)
print(x)
print('---------------------')
print(y)
print(z.shape)
print('---------------------')
print(z)

[[6 7 7]
 [5 3 9]
 [3 2 2]
 [2 9 3]]
---------------------
[1 0 2]
(4, 3)
---------------------
[[7 4 9]
 [7 8 7]
 [2 4 9]
 [2 7 1]]


In [ ]:
for i in range(4):
  z[i,:]=x[i,:]+y
print(z)

[[ 7  7  9]
 [ 6  3 11]
 [ 4  2  4]
 [ 3  9  5]]


In [ ]:
z=x+y
print(z)

[[ 7  7  9]
 [ 6  3 11]
 [ 4  2  4]
 [ 3  9  5]]


In [ ]:
a=np.array([1,2,3])
print(a)
print('-----------------')

b = np.full((6,3),[a])
print(b)
print('-----------------')

c= np.tile(a,(6,1))
print(c)

[1 2 3]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
m1 = np.random.randint(0, 10, size=(6,6))
print(m1)
aux=np.mean(m1)
print(aux)

[[0 6 7 4 8 1]
 [3 9 8 0 5 7]
 [3 5 8 8 5 3]
 [2 1 5 7 6 8]
 [7 9 5 6 0 2]
 [2 4 7 0 0 2]]
4.527777777777778


In [ ]:
np.mean(m1, axis=1)
np.mean(m1, axis=0)

print(np.mean(m1, axis=1))
print(np.mean(m1, axis=0))

[4.33333333 5.33333333 5.33333333 4.83333333 4.83333333 2.5       ]
[2.83333333 5.66666667 6.66666667 4.16666667 4.         3.83333333]
