<a href="https://colab.research.google.com/github/jampi222/inteligencia-artificial/blob/main/NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
# Import numpy as np and see the version

# your code here
import numpy as np

pass

In [ ]:
# Create a 1D array of numbers from 0 to 9
# your code here
lista=list(range(9))
print(lista)

pass

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0

vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)

pass

[0.04507964 0.28489245 0.33287752 0.49804911 0.         0.83389926
 0.56362999 0.29622543 0.30481746 0.71547349]


In [ ]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

pass

3


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])
pass

[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])
pass

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
tmp=10*np.random.random((4,4))
mascara=tmp>0
print(tmp)
print("-------------------")
print(mascara)
pass

[[2.90384324 8.2221414  1.23416637 9.89705603]
 [8.25403658 1.08290482 1.33847542 5.29716   ]
 [8.88705488 5.25963837 8.86083311 5.0515128 ]
 [8.33271837 3.77084317 4.85051395 3.00746799]]
-------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# Extract all odd numbers from arr
tmp = np.random.randint(1, 11, size=(4, 4))
print(tmp)
print('----------------------------------')
mask = np.mod(tmp, 2) == 0
print(tmp[mask])
pass

[[ 4  7 10  2]
 [ 8 10  5  6]
 [ 7 10  8  2]
 [ 4  1  1  7]]
----------------------------------
[ 4 10  2  8 10  6 10  8  2  4]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
tmp = np.arange(10,50)
print(tmp)
pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)
vectorInvertido = tmp[::-1]
print(vectorInvertido)
pass

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
tmp = np.random.randint(1, 101, size=(10, 10))
minimo = np.min(tmp)
maximo = np.max(tmp)
print("Matriz")
print(tmp)
print("Minimo")
print(minimo)
print("Maximo")
print(maximo)
pass

Matriz
[[36 20 58 35 18 59 60 14 97 58]
 [33 10 35 44  6 98 95 56 74 28]
 [79 35 46 82 76 15 99  8 57 56]
 [17 35  3 42 72 49 55 12 93 36]
 [83 67 92 17 81  7 16 19 72 39]
 [87 46 96 34 11 36 15 59 99 11]
 [67 98 86 22 76  1 54 35 11 47]
 [ 8 70 76 41 13 23 67 52 73 73]
 [47 24 68 28 55 44 57 18 71 58]
 [42  3 32 72 41 16 88 99 79 39]]
Minimo
1
Maximo
99


In [ ]:
# Create a 3x3x3 array with random values
tmp2 = np.random.random((3,3,3))
print(tmp2)
pass

[[[0.02532287 0.58746211 0.99276791]
  [0.09842987 0.82190545 0.67882362]
  [0.23171878 0.61472569 0.49007923]]

 [[0.56468038 0.17679589 0.42654151]
  [0.99877447 0.14243331 0.69334788]
  [0.25992708 0.96738694 0.10550177]]

 [[0.6118451  0.43930339 0.68948133]
  [0.24435386 0.56082893 0.6067768 ]
  [0.63489637 0.14017572 0.89028616]]]


In [ ]:
# Replace all odd numbers in arr with -1
tmp = np.random.randint(1, 11, size=(3, 3, 3))
print(tmp)
print("-----------------")
tmp[tmp % 2 == 1] = -1
print(tmp)
pass

[[[ 4  7  3]
  [ 3  8  4]
  [ 9  5  1]]

 [[ 3 10  5]
  [10 10  7]
  [ 2  2  5]]

 [[ 3 10 10]
  [ 8  6  6]
  [10  6  4]]]
-----------------
[[[ 4 -1 -1]
  [-1  8  4]
  [-1 -1 -1]]

 [[-1 10 -1]
  [10 10 -1]
  [ 2  2 -1]]

 [[-1 10 10]
  [ 8  6  6]
  [10  6  4]]]


In [ ]:
# Create an array of type float
tmpF = np.random.rand(5)
print(tmpF)
pass

[0.64222767 0.3895969  0.9878147  0.07916834 0.68063379]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
lista = list(range(12))
lista = np.array(lista)
two_d_array = lista.reshape(2, 6)
print(two_d_array)

pass

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
valoresComunes = np.intersect1d(Z1, Z2)
print(Z1)
print("-------------")
print(Z2)
print("-------------")
print(valoresComunes)
pass

[7 9 2 0 6 1 2 4 4 9]
-------------
[9 4 4 4 9 1 0 8 5 4]
-------------
[0 1 4 9]


In [ ]:
#  Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print('Array A')
print(A)
print('Array B')
print(B)

if np.array_equal(A,B):
  print('Son iguales')
else:
  print('Son diferentes')

pass

Array A
[1 1 1 0 0]
Array B
[1 1 0 1 0]
Son diferentes


In [ ]:
# Stack arrays a and b vertically
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaVertical = np.vstack((A, B))
print("Stacked Array:")
print(matrizApiladaVertical)
pass

Array A
[1 1 1 0 0]
Array B
[1 1 0 1 0]
Stacked Array:
 [[1 1 1 0 0]
 [1 1 0 1 0]]


In [ ]:
# Stack the arrays a and b horizontally.
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaHorizontal = np.hstack((A, B))
print("Stacked Array:")
print(matrizApiladaHorizontal)
pass

Array A
[1 1 1 0 0]
Array B
[1 1 0 1 0]
Stacked Array:
[1 1 1 0 0 1 1 0 1 0]


In [ ]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
print(tmp)
print('-------------')
valores = tmp[(tmp>=5)&(tmp<=10)]
print(valores)
# pass

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------
[ 5  6  7  8  9 10]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


"""Arrays"""
# a = np.array([5, 7, 9, 8, 6, 4, 5])
a = np.random.randint(1,10,7)
print("Array A")
print(a)
# b = np.array([6, 3, 4, 8, 9, 7, 1])
b = np.random.randint(1,10,7)
print("Array B")
print(b)

print("----------------------------")

"""Method 1"""
print("Method 1")
def parMax(a, b):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(a, b)

c = parMax(a, b)
print(c)

print("----------------------------")

print("Method 2")
"""Method 2"""
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

c = np.array([maxx(x, y) for x, y in zip(a, b)])
print(c)

Array A
[4 4 8 3 1 3 6]
Array B
[2 4 5 8 7 6 3]
----------------------------
Method 1
[4 4 8 8 7 6 6]
----------------------------
Method 2
[4 4 8 8 7 6 6]


In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print("------------------------")
print("Cambio de columnas 1 y 2")
print(arr)

pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------
Cambio de columnas 1 y 2
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)

[[8.57997356 9.67251033 7.13151702]
 [6.434198   6.3411781  8.95107794]
 [9.27742248 8.88833412 8.55284246]
 [5.66589409 5.46307555 5.1769449 ]
 [9.79260459 5.76907372 7.88173952]]
