<a href="https://colab.research.google.com/github/jampi222/inteligencia-artificial/blob/main/pruenaparcial2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# Create random vector of size 10 and replace the maximum value by 0
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print(random_vector)

[0.06044754 0.60258791 0.         0.31371203 0.05359179 0.28446109
 0.77379251 0.08175284 0.1240928  0.55143924]


In [3]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
element = arr[1, 2]
print( element)

8


In [4]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr = np.array([1, 2, 3, 4, 5, 6, 7])
subset = arr[2:5]
print(subset)

[3 4 5]


In [5]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr = np.array([1, 2, 3, 4, 5, 6, 7])
last_four_numbers = arr[-4:]
print(last_four_numbers)

[4 5 6 7]


In [6]:
# Create a 3×3 numpy array of all True’s
# your code here
true_array = np.ones((3, 3), dtype=bool)
print(true_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
# Extract all odd numbers from arr
# your code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


In [8]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# Reverse a vector (first element becomes last)
vector = np.array([1, 2, 3, 4, 5])
reversed_vector = vector[::-1]
print( vector)
print(reversed_vector)

[1 2 3 4 5]
[5 4 3 2 1]


In [10]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
random_array = np.random.randint(0, 100, (10, 10))
min_value = random_array.min()
max_value = random_array.max()
print(random_array)
print(min_value)
print(max_value)

[[95  3 34 57 53 30 16  3 77 80]
 [29 30 80 96 59 62 84 16 39  7]
 [58  3  4 93 92 10 91 42 58 12]
 [34 93 98 61 76 43 71 62 77 48]
 [33 74 43 87 61 98 23 80 25 73]
 [72 47 23 70 36 94 34 36 79 99]
 [39 93 31 53  0 15 85 25 10 12]
 [ 9 58 22 74 76 44 95 23 27  7]
 [29 80 47 27 92 82 33 99 61 56]
 [21 32 39 95 90 67 74 70 26  7]]
0
99


In [11]:
# Create a 3x3x3 array with random values
random_3d_array = np.random.rand(3, 3, 3)
print(random_3d_array)

[[[0.85011467 0.77261331 0.77313385]
  [0.07049631 0.55432979 0.09637443]
  [0.31975088 0.13018254 0.47008738]]

 [[0.28212728 0.84541445 0.38756959]
  [0.41092197 0.07229336 0.52974888]
  [0.1478136  0.32498859 0.66250442]]

 [[0.71015794 0.20849015 0.7165319 ]
  [0.41022706 0.57196333 0.59684725]
  [0.69744962 0.95152694 0.51837875]]]


In [12]:
# Replace all odd numbers in arr with -1
# your code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [16]:
# Create an array of type float
float_array = np.array([1.0, 2.5, 3.7, 4.2], dtype=float)
print(float_array)

[1.  2.5 3.7 4.2]


In [15]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape(2, -1)
print(original_array)
print(reshaped_array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [17]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(Z1, Z2)
print(Z1)
print(Z2)
print(common_values)

[7 5 0 1 2 5 3 7 6 2]
[0 2 9 7 4 6 8 8 4 1]
[0 1 2 6 7]


In [18]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
are_equal = np.array_equal(A, B)
print(A)
print(B)
print(are_equal)
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
elementwise_equal = np.all(A == B)
print(A)
print(B)
print(elementwise_equal)

[0 1 1 1 0]
[0 0 0 0 1]
False
[1 0 1 1 1]
[1 1 1 0 0]
False
